### ISSUE TITLE
how can i find username of Bonsai_ai API

### ISSUE THREAD

**Issue by venkatakrishnaNC** [BonsaiAI/bonsai-tutorials#3]
[error] Error while connecting to websocket: Configuration is invalid. One of the following values URL, ACCESSKEY, or USERNAME is not configured correctly. Current value for URL: wss://cp-api.bons.ai/v1/None/move_a_point/sims/ws, ACCESSKEY: d695c84160b540ddbed641e0b8c9eb34, USERNAME: None Please make sure the cli is configured correctly and/or the command line arguments are correct

the command I am running is
python .\move_a_point_simulator.py --accesskey d695c84160b540ddbed641e0b8c9eb34 --url https://cp-api.bons.ai --brain move_a_point
python version 3.6

**Comment by jostrow** [comment]
Hi @venkatakrishnaNC !  Thanks for writing.

Let's check some of the basics first:
1) Can you confirm which version of the Bonsai CLI you're using?  `pip list` should tell you.  If you're not using the latest, which I believe is 1.0.4, please upgrade it.

2) Can you try running `bonsai configure` again and making sure that completes successfully?  Then try the command again.

Thanks!

**Comment by venkatakrishnaNC** [comment]
My **bonsai_cli** version is  **1.0.4**
**bonsai configure -w my_workspace_id**
After running the above command I got the below output
No access token found in cache, please sign in.
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <code here> to authenticate.
Successfully configured

After setting it up and I tried running the command 
**python .\move_a_point_simulator.py --accesskey d695c84160b540ddbed641e0b8c9eb34 --url https://cp-api.bons.ai --brain move_a_point**

but got below output.

Request ID: 29e5fcd0-816c-441c-9535-d887c0fa1362
WARNING: ignoring failed update in Brain init.
[2020-12-18 09:12:04][error] Error while connecting to websocket: Configuration is invalid. One of the following values URL, ACCESSKEY, or USERNAME is not configured correctly. Current value for URL: wss://cp-api.bons.ai/v1/None/move_a_point/sims/ws, ACCESSKEY: d695c84160b540ddbed641e0b8c9eb34, USERNAME: None Please make sure the cli is configured correctly and/or the command line arguments are correct

**Comment by akzaidi** [comment]
hey @venkatakrishnaNC ! Apologies for your troubles. Our SDKs and our samples have moved to:
https://github.com/microsoft/microsoft-bonsai-api

You can find new samples for Python here:
https://github.com/microsoft/microsoft-bonsai-api/tree/main/Python/samples

and you can find our latest official docs here:
https://docs.bons.ai/

Unfortunately, the `move_a_point.py` sample will not work as-is with our new SDK.

**Comment by akzaidi** [comment]
Oh and our forums are actively moderated by members of the team and the community:
https://techcommunity.microsoft.com/t5/project-bonsai/ct-p/ProjectBonsai

**Comment by venkatakrishnaNC** [comment]
yeah, Thanks for the info.
